package org.purl.jh.speedsupport.conf;

import javax.swing.JCheckBox;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.DialogDescriptor;

/**
 *
 * @author jirka
 */
public class SyncPanel extends javax.swing.JPanel {
    protected DialogDescriptor desc;

    final DocumentListener listener = new DocumentListener() {
        @Override
        public void changedUpdate(DocumentEvent e) {
            changed();
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            changed();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            changed();
        }
    };




    /** Creates new form ConfPanel */
    public SyncPanel() {
        initComponents();
    }

    public void setDialogDescriptor(DialogDescriptor desc) {
        this.desc = desc;
        serverUrlField.getDocument().addDocumentListener(listener);
        userNameField.getDocument().addDocumentListener(listener);
        passwordField.getDocument().addDocumentListener(listener);
        speedFolderField.getDocument().addDocumentListener(listener);
        changed();
    }

    public String getServerUrl() {
        return serverUrlField.getText();
    }

    public void setServerUrl(String aUrl) {
        serverUrlField.setText(aUrl);
        changed();
    }

    public String getUserName() {
        return userNameField.getText();
    }

    public void setUserName(String aName) {
        userNameField.setText(aName);
        changed();
    }

    public String getUserPassword() {
        return passwordField.getText();
    }

    public void setUserPassword(String aPswd) {
        passwordField.setText(aPswd);
        changed();
    }

    public String getSpeedFolder() {
        return speedFolderField.getText();
    }

    public void setSpeedFolder(String aFolder) {
        speedFolderField.setText(aFolder);
        changed();
    }

    public boolean getReadAnySpeedFile() {
        return readAnySpeedFileCheck.isSelected();
    }

    public void setReadAnySpeedFile(boolean aSelected) {
        readAnySpeedFileCheck.setSelected(aSelected);
        //changed();
    }

    public boolean isInboxSyncEnabled() {
        return synchronizeInboxCheck.isSelected();
    }

    public boolean isInboxCheckEnabled() {
        return checkInboxEnabled.isSelected();
    }


    public void setInboxSyncEnabled(boolean aSelected) {
        this.synchronizeInboxCheck.setSelected(aSelected);
    }

    public boolean isOutboxSyncEnabled() {
        return synchronizeOutboxCheck.isSelected();
    }


    public void setOutboxSyncEnabled(boolean aSelected) {
        this.synchronizeOutboxCheck.setSelected(aSelected);
    }

    public void setInboxCheckEnabled(boolean aSelected) {
        this.checkInboxEnabled.setSelected(aSelected);
    }




    protected void changed() {
        if (desc == null) return;

        boolean valid = true;
        valid &= !serverUrlField.getText().isEmpty();
        valid &= !userNameField.getText().isEmpty();
        //valid &= passwordField.getText().isEmpty()
        valid &= !speedFolderField.getText().isEmpty();

        desc.setValid(valid);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverlUrlLabel = new javax.swing.JLabel();
        serverUrlField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        speedFolderLabel = new javax.swing.JLabel();
        speedFolderField = new javax.swing.JTextField();
        readAnySpeedFileCheck = new javax.swing.JCheckBox();
        profileLabel = new javax.swing.JLabel();
        profileCombo = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        synchronizeInboxCheck = new javax.swing.JCheckBox();
        synchronizeOutboxCheck = new javax.swing.JCheckBox();
        checkInboxEnabled = new javax.swing.JCheckBox();

        serverlUrlLabel.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.serverlUrlLabel.text")); // NOI18N

        serverUrlField.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.serverUrlField.text")); // NOI18N

        userNameLabel.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.userNameLabel.text")); // NOI18N

        userNameField.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.userNameField.text")); // NOI18N

        passwordLabel.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.passwordLabel.text")); // NOI18N

        passwordField.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.passwordField.text")); // NOI18N

        speedFolderLabel.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.speedFolderLabel.text")); // NOI18N

        speedFolderField.setEditable(false);
        speedFolderField.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.speedFolderField.text")); // NOI18N

        readAnySpeedFileCheck.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.readAnySpeedFileCheck.text")); // NOI18N
        readAnySpeedFileCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAnySpeedFileCheckActionPerformed(evt);
            }
        });

        profileLabel.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.profileLabel.text")); // NOI18N
        profileLabel.setEnabled(false);

        profileCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        profileCombo.setEnabled(false);

        synchronizeInboxCheck.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.synchronizeInboxCheck.text")); // NOI18N
        synchronizeInboxCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                synchronizeInboxCheckActionPerformed(evt);
            }
        });

        synchronizeOutboxCheck.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.synchronizeOutboxCheck.text")); // NOI18N

        checkInboxEnabled.setText(org.openide.util.NbBundle.getMessage(SyncPanel.class, "SyncPanel.checkInboxEnabled.text")); // NOI18N
        checkInboxEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInboxEnabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(synchronizeOutboxCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(serverlUrlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(speedFolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(synchronizeInboxCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addComponent(serverUrlField, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addComponent(profileCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(speedFolderField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkInboxEnabled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(readAnySpeedFileCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordField, serverUrlField, userNameField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileLabel)
                    .addComponent(profileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverlUrlLabel)
                    .addComponent(serverUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedFolderLabel)
                    .addComponent(speedFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readAnySpeedFileCheck)
                    .addComponent(synchronizeInboxCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(synchronizeOutboxCheck)
                    .addComponent(checkInboxEnabled))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordLabel, userNameLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordField, serverUrlField, speedFolderField, userNameField});

    }// </editor-fold>//GEN-END:initComponents

    private void readAnySpeedFileCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAnySpeedFileCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readAnySpeedFileCheckActionPerformed

    private void synchronizeInboxCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_synchronizeInboxCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_synchronizeInboxCheckActionPerformed

    private void checkInboxEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInboxEnabledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInboxEnabledActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkInboxEnabled;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox profileCombo;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JCheckBox readAnySpeedFileCheck;
    private javax.swing.JTextField serverUrlField;
    private javax.swing.JLabel serverlUrlLabel;
    private javax.swing.JTextField speedFolderField;
    private javax.swing.JLabel speedFolderLabel;
    private javax.swing.JCheckBox synchronizeInboxCheck;
    private javax.swing.JCheckBox synchronizeOutboxCheck;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
