package org.purl.net.jh.nb.img;

import java.awt.BorderLayout;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle;
import org.openide.windows.CloneableTopComponent;
import org.openide.windows.TopComponent;

/**
 *
 * @author jirka
 */
public class ImgTopComponent extends CloneableTopComponent {

    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/purl/net/jh/nb/img/img_pen.16.gif";

    private static final String PREFERRED_ID = "ImgTopComponent";

    //private final Zoom = new Zoom(null);

    /** Creates new ImgTopComponent */
    public ImgTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ImgTopComponent.class, "CTL_ImgTopComponent"));
        setToolTipText(NbBundle.getMessage(ImgTopComponent.class, "HINT_ImgTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
    }

    public ImgTopComponent(ImgDataObject aDObj) {
        this();
        setLayout(new BorderLayout());
        add(new ImgComponent(aDObj.getImg(), zoomControl1.getModel()), BorderLayout.CENTER);
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoomControl1 = new org.purl.net.jh.nbutil.ZoomControl();

        zoomControl1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zoomControl1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zoomControl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(483, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.purl.net.jh.nbutil.ZoomControl zoomControl1;
    // End of variables declaration//GEN-END:variables

}
