package org.purl.jh.util.gui;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author  Administrator
 */
public class TextDlg extends javax.swing.JFrame {

    /** Creates new form TextDlg */
    public TextDlg(String aTitle, String aText) {
        initComponents();
        setTitle(aTitle);
        mTextPane.setText(aText);
        mTextPane.setEditable(false);
        initUi();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mTextPane = new javax.swing.JTextPane();
        mCloseButton = new javax.swing.JButton();
        mCopyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(mTextPane);

        mCloseButton.setText("Close");
        mCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClose(evt);
            }
        });

        mCopyButton.setMnemonic('C');
        mCopyButton.setText("Copy to clipboard");
        mCopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCopy(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mCopyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mCloseButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mCloseButton, mCopyButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCloseButton)
                    .addComponent(mCopyButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmdCopy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCopy
    Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
    String s = mTextPane.getText();
    StringSelection contents = new StringSelection(s);
    cb.setContents(contents, null);
}//GEN-LAST:event_cmdCopy

private void cmdClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClose
    setVisible(false);
}//GEN-LAST:event_cmdClose


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextDlg("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mCloseButton;
    private javax.swing.JButton mCopyButton;
    private javax.swing.JTextPane mTextPane;
    // End of variables declaration//GEN-END:variables


    protected void initUi() {
        SAction okAction = new SAction("OK")     {public void a() {cmdClose(null);}};
        mCloseButton.setAction(okAction);
        
        ActionMap actionMap = rootPane.getActionMap();
        actionMap.put("actOk",     okAction);

        // --- Keybindings ---
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),  "actOk");
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "actOk");
    }

    
}
