/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Project2WOptionPanel.java
 *
 * Created on Sep 28, 2011, 12:15:08 PM
 */
package org.purl.jh.feat.iaa;

/**
 *
 * @author jirka
 */
public class Project2WOptionPanel extends javax.swing.JPanel {

    /** Creates new form Project2WOptionPanel */
    public Project2WOptionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        equalFormsCheck = new javax.swing.JCheckBox();
        equalIcFormsCheck = new javax.swing.JCheckBox();
        useWFormsPattern = new javax.swing.JCheckBox();
        wFormsPattern = new javax.swing.JTextField();
        useEPattern = new javax.swing.JCheckBox();
        eFormsPattern = new javax.swing.JTextField();
        multiFormsCheck = new javax.swing.JCheckBox();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.jLabel1.text")); // NOI18N

        equalFormsCheck.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.equalFormsCheck.text")); // NOI18N
        equalFormsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalFormsCheckActionPerformed(evt);
            }
        });

        equalIcFormsCheck.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.equalIcFormsCheck.text")); // NOI18N
        equalIcFormsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalIcFormsCheckActionPerformed(evt);
            }
        });

        useWFormsPattern.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.useWFormsPattern.text")); // NOI18N

        wFormsPattern.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.wFormsPattern.text")); // NOI18N

        useEPattern.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.useEPattern.text")); // NOI18N

        eFormsPattern.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.eFormsPattern.text")); // NOI18N

        multiFormsCheck.setText(org.openide.util.NbBundle.getMessage(Project2WOptionPanel.class, "Project2WOptionPanel.multiFormsCheck.text")); // NOI18N
        multiFormsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiFormsCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(equalFormsCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(equalIcFormsCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(useWFormsPattern, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(wFormsPattern, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(useEPattern, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(eFormsPattern, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(multiFormsCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equalFormsCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equalIcFormsCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useWFormsPattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wFormsPattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useEPattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eFormsPattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multiFormsCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void equalFormsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalFormsCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalFormsCheckActionPerformed

    private void equalIcFormsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalIcFormsCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalIcFormsCheckActionPerformed

    private void multiFormsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiFormsCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiFormsCheckActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eFormsPattern;
    private javax.swing.JCheckBox equalFormsCheck;
    private javax.swing.JCheckBox equalIcFormsCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox multiFormsCheck;
    private javax.swing.JCheckBox useEPattern;
    private javax.swing.JCheckBox useWFormsPattern;
    private javax.swing.JTextField wFormsPattern;
    // End of variables declaration//GEN-END:variables
}
